namespace GreyMatter.Poc.Pipeline;

/// <summary>
/// P0 requirement: a built-in corpus so absence of the NAS never blocks
/// development. Small and deliberately unremarkable English — it exists to keep
/// code paths exercisable, NOT to produce reportable numbers. Any result
/// measured on it must say so (Corpus.Describe stamps the source).
/// </summary>
public static class LocalSample
{
    public static readonly string[] Sentences =
    {
        "The children are asleep in the small room.",
        "I think we know what the answer is.",
        "She drinks a glass of water every morning.",
        "People are strange when you are a stranger.",
        "It is time to go home now.",
        "He sleeps for eight hours every night.",
        "The water in the river is very cold.",
        "We are going to the market this afternoon.",
        "Do you know where the station is?",
        "Time passes slowly in the quiet village.",
        "The old man sleeps in his chair.",
        "Many people think that the plan is good.",
        "You are the only one who knows.",
        "The dog drank the water from the bowl.",
        "It was so cold that the lake froze.",
        "We think it is time to leave.",
        "The boy sleeps with the light on.",
        "People in the town are very friendly.",
        "She knows the answer to the question.",
        "The water boiled in the metal pot.",
        "I am so tired that I cannot think.",
        "They are waiting for you at the door.",
        "The child sleeps soundly in the dark.",
        "We know the road to the old bridge.",
        "It takes time to learn a new language.",
        "The people are singing in the street.",
        "You think too much about small things.",
        "There is no water left in the bottle.",
        "The cat sleeps on the warm windowsill.",
        "We are so happy to see you again.",
        "Time and water flow in the same way.",
        "The teacher knows every child by name.",
        "It is hard to sleep when it is hot.",
        "People often think that money is happiness.",
        "You are late for the morning meeting.",
        "The water is deep near the far bank.",
        "We sleep early and wake before dawn.",
        "He knows that the story is not true.",
        "It is so quiet that I can hear the clock.",
        "The young people are dancing in the hall.",
        "Do you think it will rain tomorrow?",
        "The well gives clean water to the village.",
        "She sleeps badly when the wind is loud.",
        "We are the last people in the building.",
        "Time is the one thing you cannot buy.",
        "I know you are trying your best.",
        "The horse drinks water from the trough.",
        "It is time for the people to decide.",
        "You sleep too little and work too much.",
        "They know the way through the dark forest.",
        "The river water tastes of stone and moss.",
        "We think about the past far too often.",
        "People are afraid of what they do not know.",
        "It is so late that the shops are shut.",
        "The baby sleeps between her parents.",
        "You are what you do, not what you say.",
        "Time heals what words cannot reach.",
        "We know that water is life itself.",
        "The soldiers sleep in the cold field.",
        "It is the people who make the city.",
        "Do you know how much time we have?",
        "The rain water filled the empty barrel.",
        "She thinks that we are making a mistake.",
        "Everyone sleeps better in the mountain air.",
        "You are not the only one who is tired.",
        "Time in the desert moves without sound.",
        "The people know the price of bread.",
        "We drank the last of the water at noon.",
        "It is good to think before you speak.",
        "The dog sleeps at the foot of the bed.",
        "You know the sea is never really quiet.",
        "People are leaving the town in great numbers.",
        "The water rose above the garden wall.",
        "We are so far from home tonight.",
        "Time will tell whether the plan works.",
        "He sleeps with the window open in winter.",
        "I think the people are ready to listen.",
        "The cold water woke him completely.",
        "You are running out of time to decide.",
        "We know each other better than most people."
    };
}
